"""Does switching the camera model to Pinax change Fig 3's size-constancy calibration?

Simulation with P4's flat-port optics (wuwnet-fishsense2026, fishsense_wuwnet.refraction):
the true images are generated by the exact axial camera (every ray refracted through the
port), then the size-constancy estimator is run on the dot positions and the slate's apparent
size as each camera model would back-project them:

  svp     in-water single-viewpoint calibration (pinhole + radial, fitted at one depth): what the
          stored production intrinsics are
  pinax   in-air calibration + Pinax angular correction from its virtual centre of projection
  ideal   perfect perspective directions straight from the 3D points (sanity check: the estimator's own
          error under noise, with no camera model at all)

Estimator (as in slate_unknown.py / fishsense_wuwnet.laser.close_with_apparent_size): fit the dot
locus line in normalised image coordinates, regress dot position along it on apparent slate size,
take the intercept (zero size) as the vanishing point, and report its angle from the true beam.

A session: a 0.30 m slate held facing the camera with the dot on it, 10 frames at 0.6-1.8 m
(the spread of Fig 3's sessions), with optional pixel noise. Run from P4's environment:
  ../../../wuwnet-fishsense2026/.venv/bin/python sim_pinax.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[3] / "wuwnet-fishsense2026"))
from fishsense_wuwnet.refraction import (FlatPort, exit_ray, field_angle, fit_svp_model,  # noqa: E402
                                         optimal_d0, svp_scene_radius)

F_AIR = 2850.0 / 1.333                     # in-air focal length, px (production's underwater f ~ 2850)
GLASS, N_GLASS, N_WATER, HALF_FOV = 0.006, 1.49, 1.342, np.radians(40)
LASER_O = np.array([-0.031, -0.098, 0.0])  # fleet-typical laser position, m (stored extrinsics)
LASER_A = np.array([0.010, 0.020, 1.0]); LASER_A /= np.linalg.norm(LASER_A)
SLATE = 0.30


def slate_points(centre, half=SLATE / 2):
    g = np.array([[x, y, 0.0] for x in (-half, -half / 3, half / 3, half) for y in (-half, half)])
    return centre + g


def project_exact(P, port):
    """3D water points -> normalised in-air image coords (tan alpha), via the exact axial camera."""
    r = np.hypot(P[:, 0], P[:, 1]); az = np.arctan2(P[:, 1], P[:, 0])
    t = np.tan(field_angle(r, P[:, 2], port))
    return np.stack([t * np.cos(az), t * np.sin(az)], 1)


def to_directions(img, model, port, svp):
    """Normalised in-air image coords -> normalised scene directions (x/z, y/z) under a camera model."""
    t = np.hypot(img[:, 0], img[:, 1]); az = np.arctan2(img[:, 1], img[:, 0]); alpha = np.arctan(t)
    if model == "svp":
        u = svp_scene_radius(t, svp)
    else:                                   # pinax and exact share the refracted direction
        u = np.tan(exit_ray(alpha, port)[1])
    return np.stack([u * np.cos(az), u * np.sin(az)], 1)


def vanishing_error_deg(dirs, sizes):
    c = dirs.mean(0); u = np.linalg.svd(dirs - c)[2][0]
    p = (dirs - c) @ u
    slope, p_d = np.polyfit(sizes, p, 1)
    v = c + p_d * u                          # vanishing direction (x/z, y/z) at zero apparent size
    vd = np.append(v, 1.0); vd /= np.linalg.norm(vd)
    return np.degrees(np.arccos(np.clip(abs(vd @ LASER_A), -1, 1)))


def session(port, svp, Z, noise_px, rng, model):
    dirs, sizes = [], []
    for z in Z:
        t = (z - LASER_O[2]) / LASER_A[2]; dot = LASER_O + t * LASER_A
        P = np.vstack([dot, slate_points(dot + np.array([0.04, -0.03, 0.0]))])
        if model == "truth":                 # sanity check: ideal perspective directions, no refraction
            d = P[:, :2] / P[:, 2:3] + rng.normal(0, noise_px / 2850.0, (len(P), 2))
        else:
            img = project_exact(P, port) + rng.normal(0, noise_px / F_AIR, (len(P), 2))
            d = to_directions(img, model, port, svp)
        dirs.append(d[0])
        q = d[1:]; sizes.append(np.sqrt(((q - q.mean(0)) ** 2).sum(1).mean()))
    return vanishing_error_deg(np.array(dirs), np.array(sizes))


def main():
    rng = np.random.default_rng(0)
    d0, _, _ = optimal_d0(GLASS, N_GLASS, N_WATER, HALF_FOV)
    print(f"port: d0 {d0 * 1000:.1f} mm (P4 optimum), glass {GLASS * 1000:.0f} mm, n_w {N_WATER}")
    rows = []
    for d0_ in (d0, 0.020, 0.050):
        port = FlatPort(d0_, GLASS, N_GLASS, N_WATER)
        for cal_depth in (1.0, 2.0):
            svp = fit_svp_model(port, HALF_FOV, cal_depth, n_radial=2)
            for Z in (np.linspace(0.6, 1.8, 10), np.linspace(1.0, 3.0, 10)):
                for noise in (0.0, 1.0):
                    errs = {m: np.median([session(port, svp, Z, noise, rng, m) for _ in range(1 if noise == 0 else 200)])
                            for m in ("svp", "pinax", "truth")}
                    rows.append((d0_ * 1000, cal_depth, f"{Z[0]:.1f}-{Z[-1]:.1f}", noise, errs))
    print(f"{'d0 mm':>6} {'SVP cal m':>9} {'ranges m':>9} {'noise px':>8} | {'SVP':>8} {'Pinax':>8} {'ideal':>8}  (median |angle error|, deg; target 0.05)")
    for d0_, cd, Z, nz, e in rows:
        print(f"{d0_:6.1f} {cd:9.1f} {Z:>9} {nz:8.1f} | {e['svp']:8.4f} {e['pinax']:8.4f} {e['truth']:8.4f}")


if __name__ == "__main__":
    main()
